-- dmzs-mail, D1 schema.
--
-- GENERATED by scripts/gen-schema.mjs from src/schema.js. Do not edit by
-- hand: the generator overwrites this file, and deploy refuses to go ahead
-- while the two disagree. One provider, iCloud, over IMAP and SMTP spoken by
-- the Worker itself.

CREATE TABLE IF NOT EXISTS accounts (
  id          TEXT PRIMARY KEY,             -- 8 hex chars, hash of provider+email
  provider    TEXT NOT NULL,                -- icloud
  email       TEXT NOT NULL,
  label       TEXT NOT NULL DEFAULT '',     -- display name, defaults to email
  secret      TEXT,                         -- AES-GCM sealed app password
  sync_state  TEXT,                         -- per-mailbox UID cursors, JSON
  status      TEXT NOT NULL DEFAULT 'ok',   -- ok | reauth | error
  last_sync   INTEGER,                      -- ms
  last_error  TEXT,
  created_at  INTEGER NOT NULL,
  UNIQUE (provider, email)
);

CREATE TABLE IF NOT EXISTS messages (
  id          TEXT PRIMARY KEY,             -- 16 hex chars, hash of account+pid
  account_id  TEXT NOT NULL,
  pid         TEXT NOT NULL,                -- stable id: the RFC Message-ID where there is one
  mid         TEXT NOT NULL DEFAULT '',     -- RFC Message-ID, for reply threading
  thread_key  TEXT NOT NULL DEFAULT '',     -- first References id, or the normalized subject
  -- The one bucket a message is filed under, for the folder switcher:
  -- inbox | archive | sent | spam | trash | drafts, or an IMAP folder name.
  folder      TEXT NOT NULL DEFAULT 'inbox',
  from_name   TEXT NOT NULL DEFAULT '',
  from_email  TEXT NOT NULL DEFAULT '',
  to_line     TEXT NOT NULL DEFAULT '',     -- human-readable recipients
  cc_line     TEXT NOT NULL DEFAULT '',     -- copied recipients; reply-all needs them
  -- Blind recipients. Never present on mail you receive, and deliberately
  -- absent from the bytes of anything sent — a Bcc written into the message
  -- is not blind. Kept here for the two copies that are only ever yours: the
  -- draft you are still writing, and your own record of what you sent.
  bcc_line    TEXT NOT NULL DEFAULT '',
  subject     TEXT NOT NULL DEFAULT '',
  snippet     TEXT NOT NULL DEFAULT '',
  date        INTEGER NOT NULL DEFAULT 0,   -- ms
  unread      INTEGER NOT NULL DEFAULT 1,
  starred     INTEGER NOT NULL DEFAULT 0,   -- IMAP \Flagged
  has_body    INTEGER NOT NULL DEFAULT 0,   -- 1 once the defused body sits in R2
  created_at  INTEGER NOT NULL,
  UNIQUE (account_id, pid)
);

CREATE INDEX IF NOT EXISTS idx_messages_list    ON messages(folder, date DESC);

CREATE INDEX IF NOT EXISTS idx_messages_account ON messages(account_id, folder, date DESC);

CREATE INDEX IF NOT EXISTS idx_messages_thread  ON messages(thread_key);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS push_subs (
  endpoint   TEXT PRIMARY KEY,
  sub        TEXT NOT NULL,               -- the whole PushSubscription, JSON
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts_hidden (
  email      TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts_added (
  email      TEXT PRIMARY KEY,
  name       TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS blocked_senders (
  pattern    TEXT PRIMARY KEY,             -- lowercase: a whole address, or a bare domain
  n          INTEGER NOT NULL DEFAULT 0,   -- messages destroyed by this rule
  last_at    INTEGER,                      -- ms, when it last matched
  created_at INTEGER NOT NULL
);

CREATE VIRTUAL TABLE IF NOT EXISTS search USING fts5(
  id UNINDEXED,
  subject,
  sender,
  body,
  tokenize = 'unicode61 remove_diacritics 2'
);
